[package]
name = "tokenclick-tokval"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
thiserror = "1.0"
comfy-table = "7.1"
num-format = "0.4"

[dev-dependencies]
approx = "0.5"
